// File generated from our OpenAPI spec by Stainless.

package com.moderntreasury.api.models

import com.moderntreasury.api.core.JsonValue
import java.time.LocalDate
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class LegalEntityUpdateParamsTest {

    @Test
    fun create() {
        LegalEntityUpdateParams.builder()
            .id("id")
            .addAddress(
                LegalEntityAddressCreateRequest.builder()
                    .country("country")
                    .line1("line1")
                    .locality("locality")
                    .postalCode("postal_code")
                    .region("region")
                    .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                    .line2("line2")
                    .build()
            )
            .bankSettings(
                LegalEntityUpdateParams.LegalEntityBankSetting.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .backupWithholdingPercentage(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .enableBackupWithholding(true)
                    .liveMode(true)
                    .object_("object")
                    .privacyOptOut(true)
                    .regulationO(true)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
            .businessDescription("business_description")
            .businessName("business_name")
            .citizenshipCountry("citizenship_country")
            .countryOfIncorporation("country_of_incorporation")
            .dateFormed(LocalDate.parse("2019-12-27"))
            .dateOfBirth(LocalDate.parse("2019-12-27"))
            .addDoingBusinessAsName("string")
            .email("email")
            .expectedActivityVolume(0L)
            .firstName("first_name")
            .addIdentification(
                IdentificationCreateRequest.builder()
                    .idNumber("id_number")
                    .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                    .expirationDate(LocalDate.parse("2019-12-27"))
                    .issuingCountry("issuing_country")
                    .issuingRegion("issuing_region")
                    .build()
            )
            .addIndustryClassification(
                LegalEntityIndustryClassification.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addClassificationCode("string")
                    .classificationType(LegalEntityIndustryClassification.ClassificationType.ANZSIC)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .liveMode(true)
                    .object_("object")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
            .intendedUse("intended_use")
            .lastName("last_name")
            .legalStructure(LegalEntityUpdateParams.LegalStructure.CORPORATION)
            .listedExchange("listed_exchange")
            .metadata(
                LegalEntityUpdateParams.Metadata.builder()
                    .putAdditionalProperty("key", JsonValue.from("value"))
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                    .build()
            )
            .middleName("middle_name")
            .addOperatingJurisdiction("string")
            .addPhoneNumber(
                LegalEntityUpdateParams.PhoneNumber.builder().phoneNumber("phone_number").build()
            )
            .politicallyExposedPerson(true)
            .preferredName("preferred_name")
            .prefix("prefix")
            .addPrimarySocialMediaSite("string")
            .addRegulator(
                LegalEntityUpdateParams.LegalEntityRegulator.builder()
                    .jurisdiction("jurisdiction")
                    .name("name")
                    .registrationNumber("registration_number")
                    .build()
            )
            .riskRating(LegalEntityUpdateParams.RiskRating.LOW)
            .status(LegalEntityUpdateParams.Status.ACTIVE)
            .suffix("suffix")
            .thirdPartyVerification(
                LegalEntityUpdateParams.ThirdPartyVerification.builder()
                    .vendor(LegalEntityUpdateParams.ThirdPartyVerification.Vendor.PERSONA)
                    .vendorVerificationId("vendor_verification_id")
                    .build()
            )
            .tickerSymbol("ticker_symbol")
            .wealthAndEmploymentDetails(
                LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .annualIncome(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .employerCountry("employer_country")
                    .employerName("employer_name")
                    .employerState("employer_state")
                    .employmentStatus(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.EmploymentStatus
                            .EMPLOYED
                    )
                    .incomeCountry("income_country")
                    .incomeSource(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.IncomeSource
                            .FAMILY_SUPPORT
                    )
                    .incomeState("income_state")
                    .industry(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.Industry
                            .ACCOUNTING
                    )
                    .liveMode(true)
                    .object_("object")
                    .occupation(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.Occupation
                            .CONSULTING
                    )
                    .sourceOfFunds(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.SourceOfFunds
                            .ALIMONY
                    )
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .wealthSource(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.WealthSource
                            .BUSINESS_SALE
                    )
                    .build()
            )
            .website("website")
            .build()
    }

    @Test
    fun pathParams() {
        val params = LegalEntityUpdateParams.builder().id("id").build()

        assertThat(params._pathParam(0)).isEqualTo("id")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            LegalEntityUpdateParams.builder()
                .id("id")
                .addAddress(
                    LegalEntityAddressCreateRequest.builder()
                        .country("country")
                        .line1("line1")
                        .locality("locality")
                        .postalCode("postal_code")
                        .region("region")
                        .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                        .line2("line2")
                        .build()
                )
                .bankSettings(
                    LegalEntityUpdateParams.LegalEntityBankSetting.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .backupWithholdingPercentage(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .enableBackupWithholding(true)
                        .liveMode(true)
                        .object_("object")
                        .privacyOptOut(true)
                        .regulationO(true)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .businessDescription("business_description")
                .businessName("business_name")
                .citizenshipCountry("citizenship_country")
                .countryOfIncorporation("country_of_incorporation")
                .dateFormed(LocalDate.parse("2019-12-27"))
                .dateOfBirth(LocalDate.parse("2019-12-27"))
                .addDoingBusinessAsName("string")
                .email("email")
                .expectedActivityVolume(0L)
                .firstName("first_name")
                .addIdentification(
                    IdentificationCreateRequest.builder()
                        .idNumber("id_number")
                        .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                        .expirationDate(LocalDate.parse("2019-12-27"))
                        .issuingCountry("issuing_country")
                        .issuingRegion("issuing_region")
                        .build()
                )
                .addIndustryClassification(
                    LegalEntityIndustryClassification.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addClassificationCode("string")
                        .classificationType(
                            LegalEntityIndustryClassification.ClassificationType.ANZSIC
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .liveMode(true)
                        .object_("object")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .intendedUse("intended_use")
                .lastName("last_name")
                .legalStructure(LegalEntityUpdateParams.LegalStructure.CORPORATION)
                .listedExchange("listed_exchange")
                .metadata(
                    LegalEntityUpdateParams.Metadata.builder()
                        .putAdditionalProperty("key", JsonValue.from("value"))
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                        .build()
                )
                .middleName("middle_name")
                .addOperatingJurisdiction("string")
                .addPhoneNumber(
                    LegalEntityUpdateParams.PhoneNumber.builder()
                        .phoneNumber("phone_number")
                        .build()
                )
                .politicallyExposedPerson(true)
                .preferredName("preferred_name")
                .prefix("prefix")
                .addPrimarySocialMediaSite("string")
                .addRegulator(
                    LegalEntityUpdateParams.LegalEntityRegulator.builder()
                        .jurisdiction("jurisdiction")
                        .name("name")
                        .registrationNumber("registration_number")
                        .build()
                )
                .riskRating(LegalEntityUpdateParams.RiskRating.LOW)
                .status(LegalEntityUpdateParams.Status.ACTIVE)
                .suffix("suffix")
                .thirdPartyVerification(
                    LegalEntityUpdateParams.ThirdPartyVerification.builder()
                        .vendor(LegalEntityUpdateParams.ThirdPartyVerification.Vendor.PERSONA)
                        .vendorVerificationId("vendor_verification_id")
                        .build()
                )
                .tickerSymbol("ticker_symbol")
                .wealthAndEmploymentDetails(
                    LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .annualIncome(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .employerCountry("employer_country")
                        .employerName("employer_name")
                        .employerState("employer_state")
                        .employmentStatus(
                            LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail
                                .EmploymentStatus
                                .EMPLOYED
                        )
                        .incomeCountry("income_country")
                        .incomeSource(
                            LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.IncomeSource
                                .FAMILY_SUPPORT
                        )
                        .incomeState("income_state")
                        .industry(
                            LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.Industry
                                .ACCOUNTING
                        )
                        .liveMode(true)
                        .object_("object")
                        .occupation(
                            LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.Occupation
                                .CONSULTING
                        )
                        .sourceOfFunds(
                            LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.SourceOfFunds
                                .ALIMONY
                        )
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .wealthSource(
                            LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.WealthSource
                                .BUSINESS_SALE
                        )
                        .build()
                )
                .website("website")
                .build()

        val body = params._body()

        assertThat(body.addresses().getOrNull())
            .containsExactly(
                LegalEntityAddressCreateRequest.builder()
                    .country("country")
                    .line1("line1")
                    .locality("locality")
                    .postalCode("postal_code")
                    .region("region")
                    .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                    .line2("line2")
                    .build()
            )
        assertThat(body.bankSettings())
            .contains(
                LegalEntityUpdateParams.LegalEntityBankSetting.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .backupWithholdingPercentage(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .enableBackupWithholding(true)
                    .liveMode(true)
                    .object_("object")
                    .privacyOptOut(true)
                    .regulationO(true)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(body.businessDescription()).contains("business_description")
        assertThat(body.businessName()).contains("business_name")
        assertThat(body.citizenshipCountry()).contains("citizenship_country")
        assertThat(body.countryOfIncorporation()).contains("country_of_incorporation")
        assertThat(body.dateFormed()).contains(LocalDate.parse("2019-12-27"))
        assertThat(body.dateOfBirth()).contains(LocalDate.parse("2019-12-27"))
        assertThat(body.doingBusinessAsNames().getOrNull()).containsExactly("string")
        assertThat(body.email()).contains("email")
        assertThat(body.expectedActivityVolume()).contains(0L)
        assertThat(body.firstName()).contains("first_name")
        assertThat(body.identifications().getOrNull())
            .containsExactly(
                IdentificationCreateRequest.builder()
                    .idNumber("id_number")
                    .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                    .expirationDate(LocalDate.parse("2019-12-27"))
                    .issuingCountry("issuing_country")
                    .issuingRegion("issuing_region")
                    .build()
            )
        assertThat(body.industryClassifications().getOrNull())
            .containsExactly(
                LegalEntityIndustryClassification.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addClassificationCode("string")
                    .classificationType(LegalEntityIndustryClassification.ClassificationType.ANZSIC)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .liveMode(true)
                    .object_("object")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(body.intendedUse()).contains("intended_use")
        assertThat(body.lastName()).contains("last_name")
        assertThat(body.legalStructure())
            .contains(LegalEntityUpdateParams.LegalStructure.CORPORATION)
        assertThat(body.listedExchange()).contains("listed_exchange")
        assertThat(body.metadata())
            .contains(
                LegalEntityUpdateParams.Metadata.builder()
                    .putAdditionalProperty("key", JsonValue.from("value"))
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                    .build()
            )
        assertThat(body.middleName()).contains("middle_name")
        assertThat(body.operatingJurisdictions().getOrNull()).containsExactly("string")
        assertThat(body.phoneNumbers().getOrNull())
            .containsExactly(
                LegalEntityUpdateParams.PhoneNumber.builder().phoneNumber("phone_number").build()
            )
        assertThat(body.politicallyExposedPerson()).contains(true)
        assertThat(body.preferredName()).contains("preferred_name")
        assertThat(body.prefix()).contains("prefix")
        assertThat(body.primarySocialMediaSites().getOrNull()).containsExactly("string")
        assertThat(body.regulators().getOrNull())
            .containsExactly(
                LegalEntityUpdateParams.LegalEntityRegulator.builder()
                    .jurisdiction("jurisdiction")
                    .name("name")
                    .registrationNumber("registration_number")
                    .build()
            )
        assertThat(body.riskRating()).contains(LegalEntityUpdateParams.RiskRating.LOW)
        assertThat(body.status()).contains(LegalEntityUpdateParams.Status.ACTIVE)
        assertThat(body.suffix()).contains("suffix")
        assertThat(body.thirdPartyVerification())
            .contains(
                LegalEntityUpdateParams.ThirdPartyVerification.builder()
                    .vendor(LegalEntityUpdateParams.ThirdPartyVerification.Vendor.PERSONA)
                    .vendorVerificationId("vendor_verification_id")
                    .build()
            )
        assertThat(body.tickerSymbol()).contains("ticker_symbol")
        assertThat(body.wealthAndEmploymentDetails())
            .contains(
                LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .annualIncome(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .employerCountry("employer_country")
                    .employerName("employer_name")
                    .employerState("employer_state")
                    .employmentStatus(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.EmploymentStatus
                            .EMPLOYED
                    )
                    .incomeCountry("income_country")
                    .incomeSource(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.IncomeSource
                            .FAMILY_SUPPORT
                    )
                    .incomeState("income_state")
                    .industry(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.Industry
                            .ACCOUNTING
                    )
                    .liveMode(true)
                    .object_("object")
                    .occupation(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.Occupation
                            .CONSULTING
                    )
                    .sourceOfFunds(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.SourceOfFunds
                            .ALIMONY
                    )
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .wealthSource(
                        LegalEntityUpdateParams.LegalEntityWealthEmploymentDetail.WealthSource
                            .BUSINESS_SALE
                    )
                    .build()
            )
        assertThat(body.website()).contains("website")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = LegalEntityUpdateParams.builder().id("id").build()

        val body = params._body()
    }
}
