// File generated from our OpenAPI spec by Stainless.

package com.moderntreasury.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.moderntreasury.api.core.JsonValue
import com.moderntreasury.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class LegalEntityTest {

    @Test
    fun create() {
        val legalEntity =
            LegalEntity.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addAddress(
                    LegalEntity.LegalEntityAddress.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addAddressType(LegalEntity.LegalEntityAddress.AddressType.BUSINESS)
                        .country("country")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .line1("line1")
                        .line2("line2")
                        .liveMode(true)
                        .locality("locality")
                        .object_("object")
                        .postalCode("postal_code")
                        .region("region")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .bankSettings(
                    LegalEntity.LegalEntityBankSetting.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .backupWithholdingPercentage(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .enableBackupWithholding(true)
                        .liveMode(true)
                        .object_("object")
                        .privacyOptOut(true)
                        .regulationO(true)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .businessDescription("business_description")
                .businessName("business_name")
                .citizenshipCountry("citizenship_country")
                .complianceDetails(JsonValue.from(mapOf<String, Any>()))
                .countryOfIncorporation("country_of_incorporation")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dateFormed(LocalDate.parse("2019-12-27"))
                .dateOfBirth(LocalDate.parse("2019-12-27"))
                .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addDocument(
                    Document.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addDocumentDetail(
                            Document.DocumentDetail.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .documentIdentifier("document_identifier")
                                .documentIdentifierType("document_identifier_type")
                                .liveMode(true)
                                .object_("object")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .documentType("document_type")
                        .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .documentableType(Document.DocumentableType.CONNECTION)
                        .file(
                            Document.File.builder()
                                .contentType("content_type")
                                .filename("filename")
                                .size(0L)
                                .build()
                        )
                        .liveMode(true)
                        .object_("object")
                        .source("source")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .addDoingBusinessAsName("string")
                .email("email")
                .expectedActivityVolume(0L)
                .firstName("first_name")
                .addIdentification(
                    LegalEntity.Identification.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addDocument(
                            Document.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addDocumentDetail(
                                    Document.DocumentDetail.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .documentIdentifier("document_identifier")
                                        .documentIdentifierType("document_identifier_type")
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .documentType("document_type")
                                .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .documentableType(Document.DocumentableType.CONNECTION)
                                .file(
                                    Document.File.builder()
                                        .contentType("content_type")
                                        .filename("filename")
                                        .size(0L)
                                        .build()
                                )
                                .liveMode(true)
                                .object_("object")
                                .source("source")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .expirationDate(LocalDate.parse("2019-12-27"))
                        .idType(LegalEntity.Identification.IdType.AR_CUIL)
                        .issuingCountry("issuing_country")
                        .issuingRegion("issuing_region")
                        .liveMode(true)
                        .object_("object")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .addIndustryClassification(
                    LegalEntityIndustryClassification.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addClassificationCode("string")
                        .classificationType(
                            LegalEntityIndustryClassification.ClassificationType.ANZSIC
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .liveMode(true)
                        .object_("object")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .intendedUse("intended_use")
                .lastName("last_name")
                .legalEntityType(LegalEntity.LegalEntityType.BUSINESS)
                .legalStructure(LegalEntity.LegalStructure.CORPORATION)
                .listedExchange("listed_exchange")
                .liveMode(true)
                .metadata(
                    LegalEntity.Metadata.builder()
                        .putAdditionalProperty("key", JsonValue.from("value"))
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                        .build()
                )
                .middleName("middle_name")
                .object_("object")
                .addOperatingJurisdiction("string")
                .addPhoneNumber(
                    LegalEntity.PhoneNumber.builder().phoneNumber("phone_number").build()
                )
                .politicallyExposedPerson(true)
                .preferredName("preferred_name")
                .prefix("prefix")
                .addPrimarySocialMediaSite("string")
                .addRegulator(
                    LegalEntity.LegalEntityRegulator.builder()
                        .jurisdiction("jurisdiction")
                        .name("name")
                        .registrationNumber("registration_number")
                        .build()
                )
                .riskRating(LegalEntity.RiskRating.LOW)
                .status(LegalEntity.Status.ACTIVE)
                .suffix("suffix")
                .thirdPartyVerification(
                    LegalEntity.ThirdPartyVerification.builder()
                        .vendor(LegalEntity.ThirdPartyVerification.Vendor.PERSONA)
                        .vendorVerificationId("vendor_verification_id")
                        .build()
                )
                .tickerSymbol("ticker_symbol")
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .wealthAndEmploymentDetails(
                    LegalEntity.LegalEntityWealthEmploymentDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .annualIncome(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .employerCountry("employer_country")
                        .employerName("employer_name")
                        .employerState("employer_state")
                        .employmentStatus(
                            LegalEntity.LegalEntityWealthEmploymentDetail.EmploymentStatus.EMPLOYED
                        )
                        .incomeCountry("income_country")
                        .incomeSource(
                            LegalEntity.LegalEntityWealthEmploymentDetail.IncomeSource
                                .FAMILY_SUPPORT
                        )
                        .incomeState("income_state")
                        .industry(LegalEntity.LegalEntityWealthEmploymentDetail.Industry.ACCOUNTING)
                        .liveMode(true)
                        .object_("object")
                        .occupation(
                            LegalEntity.LegalEntityWealthEmploymentDetail.Occupation.CONSULTING
                        )
                        .sourceOfFunds(
                            LegalEntity.LegalEntityWealthEmploymentDetail.SourceOfFunds.ALIMONY
                        )
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .wealthSource(
                            LegalEntity.LegalEntityWealthEmploymentDetail.WealthSource.BUSINESS_SALE
                        )
                        .build()
                )
                .website("website")
                .addLegalEntityAssociation(
                    LegalEntityAssociation.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .childLegalEntity(
                            ChildLegalEntity.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addAddress(
                                    ChildLegalEntity.LegalEntityAddress.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .addAddressType(
                                            ChildLegalEntity.LegalEntityAddress.AddressType.BUSINESS
                                        )
                                        .country("country")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .line1("line1")
                                        .line2("line2")
                                        .liveMode(true)
                                        .locality("locality")
                                        .object_("object")
                                        .postalCode("postal_code")
                                        .region("region")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .bankSettings(
                                    ChildLegalEntity.LegalEntityBankSetting.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .backupWithholdingPercentage(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .enableBackupWithholding(true)
                                        .liveMode(true)
                                        .object_("object")
                                        .privacyOptOut(true)
                                        .regulationO(true)
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .businessDescription("business_description")
                                .businessName("business_name")
                                .citizenshipCountry("citizenship_country")
                                .complianceDetails(JsonValue.from(mapOf<String, Any>()))
                                .countryOfIncorporation("country_of_incorporation")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .dateFormed(LocalDate.parse("2019-12-27"))
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addDocument(
                                    Document.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .addDocumentDetail(
                                            Document.DocumentDetail.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .createdAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .discardedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .documentIdentifier("document_identifier")
                                                .documentIdentifierType("document_identifier_type")
                                                .liveMode(true)
                                                .object_("object")
                                                .updatedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                        .documentType("document_type")
                                        .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .documentableType(Document.DocumentableType.CONNECTION)
                                        .file(
                                            Document.File.builder()
                                                .contentType("content_type")
                                                .filename("filename")
                                                .size(0L)
                                                .build()
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .source("source")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .addDoingBusinessAsName("string")
                                .email("email")
                                .expectedActivityVolume(0L)
                                .firstName("first_name")
                                .addIdentification(
                                    ChildLegalEntity.Identification.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .addDocument(
                                            Document.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .createdAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .discardedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .addDocumentDetail(
                                                    Document.DocumentDetail.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .createdAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .discardedAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .documentIdentifier("document_identifier")
                                                        .documentIdentifierType(
                                                            "document_identifier_type"
                                                        )
                                                        .liveMode(true)
                                                        .object_("object")
                                                        .updatedAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .documentType("document_type")
                                                .documentableId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .documentableType(
                                                    Document.DocumentableType.CONNECTION
                                                )
                                                .file(
                                                    Document.File.builder()
                                                        .contentType("content_type")
                                                        .filename("filename")
                                                        .size(0L)
                                                        .build()
                                                )
                                                .liveMode(true)
                                                .object_("object")
                                                .source("source")
                                                .updatedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .idType(ChildLegalEntity.Identification.IdType.AR_CUIL)
                                        .issuingCountry("issuing_country")
                                        .issuingRegion("issuing_region")
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .addIndustryClassification(
                                    LegalEntityIndustryClassification.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .addClassificationCode("string")
                                        .classificationType(
                                            LegalEntityIndustryClassification.ClassificationType
                                                .ANZSIC
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .intendedUse("intended_use")
                                .lastName("last_name")
                                .legalEntityAssociations(listOf())
                                .legalEntityType(ChildLegalEntity.LegalEntityType.BUSINESS)
                                .legalStructure(ChildLegalEntity.LegalStructure.CORPORATION)
                                .listedExchange("listed_exchange")
                                .liveMode(true)
                                .metadata(
                                    ChildLegalEntity.Metadata.builder()
                                        .putAdditionalProperty("key", JsonValue.from("value"))
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                        .build()
                                )
                                .middleName("middle_name")
                                .object_("object")
                                .addOperatingJurisdiction("string")
                                .addPhoneNumber(
                                    ChildLegalEntity.PhoneNumber.builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .politicallyExposedPerson(true)
                                .preferredName("preferred_name")
                                .prefix("prefix")
                                .addPrimarySocialMediaSite("string")
                                .addRegulator(
                                    ChildLegalEntity.LegalEntityRegulator.builder()
                                        .jurisdiction("jurisdiction")
                                        .name("name")
                                        .registrationNumber("registration_number")
                                        .build()
                                )
                                .riskRating(ChildLegalEntity.RiskRating.LOW)
                                .status(ChildLegalEntity.Status.ACTIVE)
                                .suffix("suffix")
                                .thirdPartyVerification(
                                    ChildLegalEntity.ThirdPartyVerification.builder()
                                        .vendor(
                                            ChildLegalEntity.ThirdPartyVerification.Vendor.PERSONA
                                        )
                                        .vendorVerificationId("vendor_verification_id")
                                        .build()
                                )
                                .tickerSymbol("ticker_symbol")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .wealthAndEmploymentDetails(
                                    ChildLegalEntity.LegalEntityWealthEmploymentDetail.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .annualIncome(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .employerCountry("employer_country")
                                        .employerName("employer_name")
                                        .employerState("employer_state")
                                        .employmentStatus(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .EmploymentStatus
                                                .EMPLOYED
                                        )
                                        .incomeCountry("income_country")
                                        .incomeSource(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .IncomeSource
                                                .FAMILY_SUPPORT
                                        )
                                        .incomeState("income_state")
                                        .industry(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .Industry
                                                .ACCOUNTING
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .occupation(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .Occupation
                                                .CONSULTING
                                        )
                                        .sourceOfFunds(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .SourceOfFunds
                                                .ALIMONY
                                        )
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .wealthSource(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .WealthSource
                                                .BUSINESS_SALE
                                        )
                                        .build()
                                )
                                .website("website")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .liveMode(true)
                        .object_("object")
                        .ownershipPercentage(0L)
                        .parentLegalEntityId("parent_legal_entity_id")
                        .addRelationshipType(
                            LegalEntityAssociation.RelationshipType.AUTHORIZED_SIGNER
                        )
                        .title("title")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .build()

        assertThat(legalEntity.id()).isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
        assertThat(legalEntity.addresses())
            .containsExactly(
                LegalEntity.LegalEntityAddress.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addAddressType(LegalEntity.LegalEntityAddress.AddressType.BUSINESS)
                    .country("country")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .line1("line1")
                    .line2("line2")
                    .liveMode(true)
                    .locality("locality")
                    .object_("object")
                    .postalCode("postal_code")
                    .region("region")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(legalEntity.bankSettings())
            .contains(
                LegalEntity.LegalEntityBankSetting.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .backupWithholdingPercentage(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .enableBackupWithholding(true)
                    .liveMode(true)
                    .object_("object")
                    .privacyOptOut(true)
                    .regulationO(true)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(legalEntity.businessDescription()).contains("business_description")
        assertThat(legalEntity.businessName()).contains("business_name")
        assertThat(legalEntity.citizenshipCountry()).contains("citizenship_country")
        assertThat(legalEntity._complianceDetails()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(legalEntity.countryOfIncorporation()).contains("country_of_incorporation")
        assertThat(legalEntity.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(legalEntity.dateFormed()).contains(LocalDate.parse("2019-12-27"))
        assertThat(legalEntity.dateOfBirth()).contains(LocalDate.parse("2019-12-27"))
        assertThat(legalEntity.discardedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(legalEntity.documents())
            .containsExactly(
                Document.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addDocumentDetail(
                        Document.DocumentDetail.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .documentIdentifier("document_identifier")
                            .documentIdentifierType("document_identifier_type")
                            .liveMode(true)
                            .object_("object")
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .documentType("document_type")
                    .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .documentableType(Document.DocumentableType.CONNECTION)
                    .file(
                        Document.File.builder()
                            .contentType("content_type")
                            .filename("filename")
                            .size(0L)
                            .build()
                    )
                    .liveMode(true)
                    .object_("object")
                    .source("source")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(legalEntity.doingBusinessAsNames()).containsExactly("string")
        assertThat(legalEntity.email()).contains("email")
        assertThat(legalEntity.expectedActivityVolume()).contains(0L)
        assertThat(legalEntity.firstName()).contains("first_name")
        assertThat(legalEntity.identifications())
            .containsExactly(
                LegalEntity.Identification.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addDocument(
                        Document.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addDocumentDetail(
                                Document.DocumentDetail.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .documentIdentifier("document_identifier")
                                    .documentIdentifierType("document_identifier_type")
                                    .liveMode(true)
                                    .object_("object")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .documentType("document_type")
                            .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .documentableType(Document.DocumentableType.CONNECTION)
                            .file(
                                Document.File.builder()
                                    .contentType("content_type")
                                    .filename("filename")
                                    .size(0L)
                                    .build()
                            )
                            .liveMode(true)
                            .object_("object")
                            .source("source")
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .expirationDate(LocalDate.parse("2019-12-27"))
                    .idType(LegalEntity.Identification.IdType.AR_CUIL)
                    .issuingCountry("issuing_country")
                    .issuingRegion("issuing_region")
                    .liveMode(true)
                    .object_("object")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(legalEntity.industryClassifications())
            .containsExactly(
                LegalEntityIndustryClassification.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addClassificationCode("string")
                    .classificationType(LegalEntityIndustryClassification.ClassificationType.ANZSIC)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .liveMode(true)
                    .object_("object")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(legalEntity.intendedUse()).contains("intended_use")
        assertThat(legalEntity.lastName()).contains("last_name")
        assertThat(legalEntity.legalEntityType()).isEqualTo(LegalEntity.LegalEntityType.BUSINESS)
        assertThat(legalEntity.legalStructure()).contains(LegalEntity.LegalStructure.CORPORATION)
        assertThat(legalEntity.listedExchange()).contains("listed_exchange")
        assertThat(legalEntity.liveMode()).isEqualTo(true)
        assertThat(legalEntity.metadata())
            .isEqualTo(
                LegalEntity.Metadata.builder()
                    .putAdditionalProperty("key", JsonValue.from("value"))
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                    .build()
            )
        assertThat(legalEntity.middleName()).contains("middle_name")
        assertThat(legalEntity.object_()).isEqualTo("object")
        assertThat(legalEntity.operatingJurisdictions()).containsExactly("string")
        assertThat(legalEntity.phoneNumbers())
            .containsExactly(LegalEntity.PhoneNumber.builder().phoneNumber("phone_number").build())
        assertThat(legalEntity.politicallyExposedPerson()).contains(true)
        assertThat(legalEntity.preferredName()).contains("preferred_name")
        assertThat(legalEntity.prefix()).contains("prefix")
        assertThat(legalEntity.primarySocialMediaSites()).containsExactly("string")
        assertThat(legalEntity.regulators().getOrNull())
            .containsExactly(
                LegalEntity.LegalEntityRegulator.builder()
                    .jurisdiction("jurisdiction")
                    .name("name")
                    .registrationNumber("registration_number")
                    .build()
            )
        assertThat(legalEntity.riskRating()).contains(LegalEntity.RiskRating.LOW)
        assertThat(legalEntity.status()).contains(LegalEntity.Status.ACTIVE)
        assertThat(legalEntity.suffix()).contains("suffix")
        assertThat(legalEntity.thirdPartyVerification())
            .contains(
                LegalEntity.ThirdPartyVerification.builder()
                    .vendor(LegalEntity.ThirdPartyVerification.Vendor.PERSONA)
                    .vendorVerificationId("vendor_verification_id")
                    .build()
            )
        assertThat(legalEntity.tickerSymbol()).contains("ticker_symbol")
        assertThat(legalEntity.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(legalEntity.wealthAndEmploymentDetails())
            .contains(
                LegalEntity.LegalEntityWealthEmploymentDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .annualIncome(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .employerCountry("employer_country")
                    .employerName("employer_name")
                    .employerState("employer_state")
                    .employmentStatus(
                        LegalEntity.LegalEntityWealthEmploymentDetail.EmploymentStatus.EMPLOYED
                    )
                    .incomeCountry("income_country")
                    .incomeSource(
                        LegalEntity.LegalEntityWealthEmploymentDetail.IncomeSource.FAMILY_SUPPORT
                    )
                    .incomeState("income_state")
                    .industry(LegalEntity.LegalEntityWealthEmploymentDetail.Industry.ACCOUNTING)
                    .liveMode(true)
                    .object_("object")
                    .occupation(LegalEntity.LegalEntityWealthEmploymentDetail.Occupation.CONSULTING)
                    .sourceOfFunds(
                        LegalEntity.LegalEntityWealthEmploymentDetail.SourceOfFunds.ALIMONY
                    )
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .wealthSource(
                        LegalEntity.LegalEntityWealthEmploymentDetail.WealthSource.BUSINESS_SALE
                    )
                    .build()
            )
        assertThat(legalEntity.website()).contains("website")
        assertThat(legalEntity.legalEntityAssociations().getOrNull())
            .containsExactly(
                LegalEntityAssociation.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .childLegalEntity(
                        ChildLegalEntity.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .addAddress(
                                ChildLegalEntity.LegalEntityAddress.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addAddressType(
                                        ChildLegalEntity.LegalEntityAddress.AddressType.BUSINESS
                                    )
                                    .country("country")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .line1("line1")
                                    .line2("line2")
                                    .liveMode(true)
                                    .locality("locality")
                                    .object_("object")
                                    .postalCode("postal_code")
                                    .region("region")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .bankSettings(
                                ChildLegalEntity.LegalEntityBankSetting.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .backupWithholdingPercentage(0L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .enableBackupWithholding(true)
                                    .liveMode(true)
                                    .object_("object")
                                    .privacyOptOut(true)
                                    .regulationO(true)
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .businessDescription("business_description")
                            .businessName("business_name")
                            .citizenshipCountry("citizenship_country")
                            .complianceDetails(JsonValue.from(mapOf<String, Any>()))
                            .countryOfIncorporation("country_of_incorporation")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .dateFormed(LocalDate.parse("2019-12-27"))
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addDocument(
                                Document.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .addDocumentDetail(
                                        Document.DocumentDetail.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .createdAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .discardedAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .documentIdentifier("document_identifier")
                                            .documentIdentifierType("document_identifier_type")
                                            .liveMode(true)
                                            .object_("object")
                                            .updatedAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .documentType("document_type")
                                    .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .documentableType(Document.DocumentableType.CONNECTION)
                                    .file(
                                        Document.File.builder()
                                            .contentType("content_type")
                                            .filename("filename")
                                            .size(0L)
                                            .build()
                                    )
                                    .liveMode(true)
                                    .object_("object")
                                    .source("source")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .addDoingBusinessAsName("string")
                            .email("email")
                            .expectedActivityVolume(0L)
                            .firstName("first_name")
                            .addIdentification(
                                ChildLegalEntity.Identification.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .addDocument(
                                        Document.builder()
                                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .createdAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .discardedAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .addDocumentDetail(
                                                Document.DocumentDetail.builder()
                                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                    .createdAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .discardedAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .documentIdentifier("document_identifier")
                                                    .documentIdentifierType(
                                                        "document_identifier_type"
                                                    )
                                                    .liveMode(true)
                                                    .object_("object")
                                                    .updatedAt(
                                                        OffsetDateTime.parse(
                                                            "2019-12-27T18:11:19.117Z"
                                                        )
                                                    )
                                                    .build()
                                            )
                                            .documentType("document_type")
                                            .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                            .documentableType(Document.DocumentableType.CONNECTION)
                                            .file(
                                                Document.File.builder()
                                                    .contentType("content_type")
                                                    .filename("filename")
                                                    .size(0L)
                                                    .build()
                                            )
                                            .liveMode(true)
                                            .object_("object")
                                            .source("source")
                                            .updatedAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .build()
                                    )
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .idType(ChildLegalEntity.Identification.IdType.AR_CUIL)
                                    .issuingCountry("issuing_country")
                                    .issuingRegion("issuing_region")
                                    .liveMode(true)
                                    .object_("object")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .addIndustryClassification(
                                LegalEntityIndustryClassification.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addClassificationCode("string")
                                    .classificationType(
                                        LegalEntityIndustryClassification.ClassificationType.ANZSIC
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .liveMode(true)
                                    .object_("object")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .intendedUse("intended_use")
                            .lastName("last_name")
                            .legalEntityAssociations(listOf())
                            .legalEntityType(ChildLegalEntity.LegalEntityType.BUSINESS)
                            .legalStructure(ChildLegalEntity.LegalStructure.CORPORATION)
                            .listedExchange("listed_exchange")
                            .liveMode(true)
                            .metadata(
                                ChildLegalEntity.Metadata.builder()
                                    .putAdditionalProperty("key", JsonValue.from("value"))
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                    .build()
                            )
                            .middleName("middle_name")
                            .object_("object")
                            .addOperatingJurisdiction("string")
                            .addPhoneNumber(
                                ChildLegalEntity.PhoneNumber.builder()
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .politicallyExposedPerson(true)
                            .preferredName("preferred_name")
                            .prefix("prefix")
                            .addPrimarySocialMediaSite("string")
                            .addRegulator(
                                ChildLegalEntity.LegalEntityRegulator.builder()
                                    .jurisdiction("jurisdiction")
                                    .name("name")
                                    .registrationNumber("registration_number")
                                    .build()
                            )
                            .riskRating(ChildLegalEntity.RiskRating.LOW)
                            .status(ChildLegalEntity.Status.ACTIVE)
                            .suffix("suffix")
                            .thirdPartyVerification(
                                ChildLegalEntity.ThirdPartyVerification.builder()
                                    .vendor(ChildLegalEntity.ThirdPartyVerification.Vendor.PERSONA)
                                    .vendorVerificationId("vendor_verification_id")
                                    .build()
                            )
                            .tickerSymbol("ticker_symbol")
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .wealthAndEmploymentDetails(
                                ChildLegalEntity.LegalEntityWealthEmploymentDetail.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .annualIncome(0L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .employerCountry("employer_country")
                                    .employerName("employer_name")
                                    .employerState("employer_state")
                                    .employmentStatus(
                                        ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                            .EmploymentStatus
                                            .EMPLOYED
                                    )
                                    .incomeCountry("income_country")
                                    .incomeSource(
                                        ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                            .IncomeSource
                                            .FAMILY_SUPPORT
                                    )
                                    .incomeState("income_state")
                                    .industry(
                                        ChildLegalEntity.LegalEntityWealthEmploymentDetail.Industry
                                            .ACCOUNTING
                                    )
                                    .liveMode(true)
                                    .object_("object")
                                    .occupation(
                                        ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                            .Occupation
                                            .CONSULTING
                                    )
                                    .sourceOfFunds(
                                        ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                            .SourceOfFunds
                                            .ALIMONY
                                    )
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .wealthSource(
                                        ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                            .WealthSource
                                            .BUSINESS_SALE
                                    )
                                    .build()
                            )
                            .website("website")
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .liveMode(true)
                    .object_("object")
                    .ownershipPercentage(0L)
                    .parentLegalEntityId("parent_legal_entity_id")
                    .addRelationshipType(LegalEntityAssociation.RelationshipType.AUTHORIZED_SIGNER)
                    .title("title")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val legalEntity =
            LegalEntity.builder()
                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .addAddress(
                    LegalEntity.LegalEntityAddress.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addAddressType(LegalEntity.LegalEntityAddress.AddressType.BUSINESS)
                        .country("country")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .line1("line1")
                        .line2("line2")
                        .liveMode(true)
                        .locality("locality")
                        .object_("object")
                        .postalCode("postal_code")
                        .region("region")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .bankSettings(
                    LegalEntity.LegalEntityBankSetting.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .backupWithholdingPercentage(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .enableBackupWithholding(true)
                        .liveMode(true)
                        .object_("object")
                        .privacyOptOut(true)
                        .regulationO(true)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .businessDescription("business_description")
                .businessName("business_name")
                .citizenshipCountry("citizenship_country")
                .complianceDetails(JsonValue.from(mapOf<String, Any>()))
                .countryOfIncorporation("country_of_incorporation")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dateFormed(LocalDate.parse("2019-12-27"))
                .dateOfBirth(LocalDate.parse("2019-12-27"))
                .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addDocument(
                    Document.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addDocumentDetail(
                            Document.DocumentDetail.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .documentIdentifier("document_identifier")
                                .documentIdentifierType("document_identifier_type")
                                .liveMode(true)
                                .object_("object")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .documentType("document_type")
                        .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .documentableType(Document.DocumentableType.CONNECTION)
                        .file(
                            Document.File.builder()
                                .contentType("content_type")
                                .filename("filename")
                                .size(0L)
                                .build()
                        )
                        .liveMode(true)
                        .object_("object")
                        .source("source")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .addDoingBusinessAsName("string")
                .email("email")
                .expectedActivityVolume(0L)
                .firstName("first_name")
                .addIdentification(
                    LegalEntity.Identification.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addDocument(
                            Document.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addDocumentDetail(
                                    Document.DocumentDetail.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .documentIdentifier("document_identifier")
                                        .documentIdentifierType("document_identifier_type")
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .documentType("document_type")
                                .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .documentableType(Document.DocumentableType.CONNECTION)
                                .file(
                                    Document.File.builder()
                                        .contentType("content_type")
                                        .filename("filename")
                                        .size(0L)
                                        .build()
                                )
                                .liveMode(true)
                                .object_("object")
                                .source("source")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .expirationDate(LocalDate.parse("2019-12-27"))
                        .idType(LegalEntity.Identification.IdType.AR_CUIL)
                        .issuingCountry("issuing_country")
                        .issuingRegion("issuing_region")
                        .liveMode(true)
                        .object_("object")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .addIndustryClassification(
                    LegalEntityIndustryClassification.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addClassificationCode("string")
                        .classificationType(
                            LegalEntityIndustryClassification.ClassificationType.ANZSIC
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .liveMode(true)
                        .object_("object")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .intendedUse("intended_use")
                .lastName("last_name")
                .legalEntityType(LegalEntity.LegalEntityType.BUSINESS)
                .legalStructure(LegalEntity.LegalStructure.CORPORATION)
                .listedExchange("listed_exchange")
                .liveMode(true)
                .metadata(
                    LegalEntity.Metadata.builder()
                        .putAdditionalProperty("key", JsonValue.from("value"))
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                        .build()
                )
                .middleName("middle_name")
                .object_("object")
                .addOperatingJurisdiction("string")
                .addPhoneNumber(
                    LegalEntity.PhoneNumber.builder().phoneNumber("phone_number").build()
                )
                .politicallyExposedPerson(true)
                .preferredName("preferred_name")
                .prefix("prefix")
                .addPrimarySocialMediaSite("string")
                .addRegulator(
                    LegalEntity.LegalEntityRegulator.builder()
                        .jurisdiction("jurisdiction")
                        .name("name")
                        .registrationNumber("registration_number")
                        .build()
                )
                .riskRating(LegalEntity.RiskRating.LOW)
                .status(LegalEntity.Status.ACTIVE)
                .suffix("suffix")
                .thirdPartyVerification(
                    LegalEntity.ThirdPartyVerification.builder()
                        .vendor(LegalEntity.ThirdPartyVerification.Vendor.PERSONA)
                        .vendorVerificationId("vendor_verification_id")
                        .build()
                )
                .tickerSymbol("ticker_symbol")
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .wealthAndEmploymentDetails(
                    LegalEntity.LegalEntityWealthEmploymentDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .annualIncome(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .employerCountry("employer_country")
                        .employerName("employer_name")
                        .employerState("employer_state")
                        .employmentStatus(
                            LegalEntity.LegalEntityWealthEmploymentDetail.EmploymentStatus.EMPLOYED
                        )
                        .incomeCountry("income_country")
                        .incomeSource(
                            LegalEntity.LegalEntityWealthEmploymentDetail.IncomeSource
                                .FAMILY_SUPPORT
                        )
                        .incomeState("income_state")
                        .industry(LegalEntity.LegalEntityWealthEmploymentDetail.Industry.ACCOUNTING)
                        .liveMode(true)
                        .object_("object")
                        .occupation(
                            LegalEntity.LegalEntityWealthEmploymentDetail.Occupation.CONSULTING
                        )
                        .sourceOfFunds(
                            LegalEntity.LegalEntityWealthEmploymentDetail.SourceOfFunds.ALIMONY
                        )
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .wealthSource(
                            LegalEntity.LegalEntityWealthEmploymentDetail.WealthSource.BUSINESS_SALE
                        )
                        .build()
                )
                .website("website")
                .addLegalEntityAssociation(
                    LegalEntityAssociation.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .childLegalEntity(
                            ChildLegalEntity.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .addAddress(
                                    ChildLegalEntity.LegalEntityAddress.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .addAddressType(
                                            ChildLegalEntity.LegalEntityAddress.AddressType.BUSINESS
                                        )
                                        .country("country")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .line1("line1")
                                        .line2("line2")
                                        .liveMode(true)
                                        .locality("locality")
                                        .object_("object")
                                        .postalCode("postal_code")
                                        .region("region")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .bankSettings(
                                    ChildLegalEntity.LegalEntityBankSetting.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .backupWithholdingPercentage(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .enableBackupWithholding(true)
                                        .liveMode(true)
                                        .object_("object")
                                        .privacyOptOut(true)
                                        .regulationO(true)
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .businessDescription("business_description")
                                .businessName("business_name")
                                .citizenshipCountry("citizenship_country")
                                .complianceDetails(JsonValue.from(mapOf<String, Any>()))
                                .countryOfIncorporation("country_of_incorporation")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .dateFormed(LocalDate.parse("2019-12-27"))
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addDocument(
                                    Document.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .addDocumentDetail(
                                            Document.DocumentDetail.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .createdAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .discardedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .documentIdentifier("document_identifier")
                                                .documentIdentifierType("document_identifier_type")
                                                .liveMode(true)
                                                .object_("object")
                                                .updatedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                        .documentType("document_type")
                                        .documentableId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .documentableType(Document.DocumentableType.CONNECTION)
                                        .file(
                                            Document.File.builder()
                                                .contentType("content_type")
                                                .filename("filename")
                                                .size(0L)
                                                .build()
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .source("source")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .addDoingBusinessAsName("string")
                                .email("email")
                                .expectedActivityVolume(0L)
                                .firstName("first_name")
                                .addIdentification(
                                    ChildLegalEntity.Identification.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .addDocument(
                                            Document.builder()
                                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                .createdAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .discardedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .addDocumentDetail(
                                                    Document.DocumentDetail.builder()
                                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                                        .createdAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .discardedAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .documentIdentifier("document_identifier")
                                                        .documentIdentifierType(
                                                            "document_identifier_type"
                                                        )
                                                        .liveMode(true)
                                                        .object_("object")
                                                        .updatedAt(
                                                            OffsetDateTime.parse(
                                                                "2019-12-27T18:11:19.117Z"
                                                            )
                                                        )
                                                        .build()
                                                )
                                                .documentType("document_type")
                                                .documentableId(
                                                    "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e"
                                                )
                                                .documentableType(
                                                    Document.DocumentableType.CONNECTION
                                                )
                                                .file(
                                                    Document.File.builder()
                                                        .contentType("content_type")
                                                        .filename("filename")
                                                        .size(0L)
                                                        .build()
                                                )
                                                .liveMode(true)
                                                .object_("object")
                                                .source("source")
                                                .updatedAt(
                                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                                )
                                                .build()
                                        )
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .idType(ChildLegalEntity.Identification.IdType.AR_CUIL)
                                        .issuingCountry("issuing_country")
                                        .issuingRegion("issuing_region")
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .addIndustryClassification(
                                    LegalEntityIndustryClassification.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .addClassificationCode("string")
                                        .classificationType(
                                            LegalEntityIndustryClassification.ClassificationType
                                                .ANZSIC
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .intendedUse("intended_use")
                                .lastName("last_name")
                                .legalEntityAssociations(listOf())
                                .legalEntityType(ChildLegalEntity.LegalEntityType.BUSINESS)
                                .legalStructure(ChildLegalEntity.LegalStructure.CORPORATION)
                                .listedExchange("listed_exchange")
                                .liveMode(true)
                                .metadata(
                                    ChildLegalEntity.Metadata.builder()
                                        .putAdditionalProperty("key", JsonValue.from("value"))
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                        .build()
                                )
                                .middleName("middle_name")
                                .object_("object")
                                .addOperatingJurisdiction("string")
                                .addPhoneNumber(
                                    ChildLegalEntity.PhoneNumber.builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .politicallyExposedPerson(true)
                                .preferredName("preferred_name")
                                .prefix("prefix")
                                .addPrimarySocialMediaSite("string")
                                .addRegulator(
                                    ChildLegalEntity.LegalEntityRegulator.builder()
                                        .jurisdiction("jurisdiction")
                                        .name("name")
                                        .registrationNumber("registration_number")
                                        .build()
                                )
                                .riskRating(ChildLegalEntity.RiskRating.LOW)
                                .status(ChildLegalEntity.Status.ACTIVE)
                                .suffix("suffix")
                                .thirdPartyVerification(
                                    ChildLegalEntity.ThirdPartyVerification.builder()
                                        .vendor(
                                            ChildLegalEntity.ThirdPartyVerification.Vendor.PERSONA
                                        )
                                        .vendorVerificationId("vendor_verification_id")
                                        .build()
                                )
                                .tickerSymbol("ticker_symbol")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .wealthAndEmploymentDetails(
                                    ChildLegalEntity.LegalEntityWealthEmploymentDetail.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .annualIncome(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .employerCountry("employer_country")
                                        .employerName("employer_name")
                                        .employerState("employer_state")
                                        .employmentStatus(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .EmploymentStatus
                                                .EMPLOYED
                                        )
                                        .incomeCountry("income_country")
                                        .incomeSource(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .IncomeSource
                                                .FAMILY_SUPPORT
                                        )
                                        .incomeState("income_state")
                                        .industry(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .Industry
                                                .ACCOUNTING
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .occupation(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .Occupation
                                                .CONSULTING
                                        )
                                        .sourceOfFunds(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .SourceOfFunds
                                                .ALIMONY
                                        )
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .wealthSource(
                                            ChildLegalEntity.LegalEntityWealthEmploymentDetail
                                                .WealthSource
                                                .BUSINESS_SALE
                                        )
                                        .build()
                                )
                                .website("website")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .liveMode(true)
                        .object_("object")
                        .ownershipPercentage(0L)
                        .parentLegalEntityId("parent_legal_entity_id")
                        .addRelationshipType(
                            LegalEntityAssociation.RelationshipType.AUTHORIZED_SIGNER
                        )
                        .title("title")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .build()

        val roundtrippedLegalEntity =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(legalEntity),
                jacksonTypeRef<LegalEntity>(),
            )

        assertThat(roundtrippedLegalEntity).isEqualTo(legalEntity)
    }
}
