// File generated from our OpenAPI spec by Stainless.

package com.moderntreasury.api.models

import com.moderntreasury.api.core.JsonValue
import java.time.LocalDate
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class LegalEntityCreateParamsTest {

    @Test
    fun create() {
        LegalEntityCreateParams.builder()
            .legalEntityType(LegalEntityCreateParams.LegalEntityType.BUSINESS)
            .addAddress(
                LegalEntityAddressCreateRequest.builder()
                    .country("country")
                    .line1("line1")
                    .locality("locality")
                    .postalCode("postal_code")
                    .region("region")
                    .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                    .line2("line2")
                    .build()
            )
            .bankSettings(
                LegalEntityCreateParams.LegalEntityBankSetting.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .backupWithholdingPercentage(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .enableBackupWithholding(true)
                    .liveMode(true)
                    .object_("object")
                    .privacyOptOut(true)
                    .regulationO(true)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
            .businessDescription("business_description")
            .businessName("business_name")
            .citizenshipCountry("citizenship_country")
            .complianceDetails(
                LegalEntityComplianceDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .issuer("issuer")
                    .liveMode(true)
                    .object_("object")
                    .tokenExpiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .tokenUrl("token_url")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .entityValidated(true)
                    .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
            .countryOfIncorporation("country_of_incorporation")
            .dateFormed(LocalDate.parse("2019-12-27"))
            .dateOfBirth(LocalDate.parse("2019-12-27"))
            .addDoingBusinessAsName("string")
            .email("email")
            .expectedActivityVolume(0L)
            .firstName("first_name")
            .addIdentification(
                IdentificationCreateRequest.builder()
                    .idNumber("id_number")
                    .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                    .expirationDate(LocalDate.parse("2019-12-27"))
                    .issuingCountry("issuing_country")
                    .issuingRegion("issuing_region")
                    .build()
            )
            .addIndustryClassification(
                LegalEntityIndustryClassification.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addClassificationCode("string")
                    .classificationType(LegalEntityIndustryClassification.ClassificationType.ANZSIC)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .liveMode(true)
                    .object_("object")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
            .intendedUse("intended_use")
            .lastName("last_name")
            .addLegalEntityAssociation(
                LegalEntityAssociationInlineCreate.builder()
                    .addRelationshipType(
                        LegalEntityAssociationInlineCreate.RelationshipType.AUTHORIZED_SIGNER
                    )
                    .childLegalEntity(
                        ChildLegalEntityCreate.builder()
                            .addAddress(
                                LegalEntityAddressCreateRequest.builder()
                                    .country("country")
                                    .line1("line1")
                                    .locality("locality")
                                    .postalCode("postal_code")
                                    .region("region")
                                    .addAddressType(
                                        LegalEntityAddressCreateRequest.AddressType.BUSINESS
                                    )
                                    .line2("line2")
                                    .build()
                            )
                            .bankSettings(
                                ChildLegalEntityCreate.LegalEntityBankSetting.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .backupWithholdingPercentage(0L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .enableBackupWithholding(true)
                                    .liveMode(true)
                                    .object_("object")
                                    .privacyOptOut(true)
                                    .regulationO(true)
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .businessDescription("business_description")
                            .businessName("business_name")
                            .citizenshipCountry("citizenship_country")
                            .complianceDetails(
                                LegalEntityComplianceDetail.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .issuer("issuer")
                                    .liveMode(true)
                                    .object_("object")
                                    .tokenExpiresAt(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .tokenUrl("token_url")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .entityValidated(true)
                                    .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .countryOfIncorporation("country_of_incorporation")
                            .dateFormed(LocalDate.parse("2019-12-27"))
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .addDoingBusinessAsName("string")
                            .email("email")
                            .expectedActivityVolume(0L)
                            .firstName("first_name")
                            .addIdentification(
                                IdentificationCreateRequest.builder()
                                    .idNumber("id_number")
                                    .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .issuingCountry("issuing_country")
                                    .issuingRegion("issuing_region")
                                    .build()
                            )
                            .addIndustryClassification(
                                LegalEntityIndustryClassification.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addClassificationCode("string")
                                    .classificationType(
                                        LegalEntityIndustryClassification.ClassificationType.ANZSIC
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .liveMode(true)
                                    .object_("object")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .intendedUse("intended_use")
                            .lastName("last_name")
                            .legalEntityAssociations(listOf())
                            .legalEntityType(ChildLegalEntityCreate.LegalEntityType.BUSINESS)
                            .legalStructure(ChildLegalEntityCreate.LegalStructure.CORPORATION)
                            .metadata(
                                ChildLegalEntityCreate.Metadata.builder()
                                    .putAdditionalProperty("key", JsonValue.from("value"))
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                    .build()
                            )
                            .middleName("middle_name")
                            .addOperatingJurisdiction("string")
                            .addPhoneNumber(
                                ChildLegalEntityCreate.PhoneNumber.builder()
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .politicallyExposedPerson(true)
                            .preferredName("preferred_name")
                            .prefix("prefix")
                            .addPrimarySocialMediaSite("string")
                            .riskRating(ChildLegalEntityCreate.RiskRating.LOW)
                            .suffix("suffix")
                            .wealthAndEmploymentDetails(
                                ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .annualIncome(0L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .employerCountry("employer_country")
                                    .employerName("employer_name")
                                    .employerState("employer_state")
                                    .employmentStatus(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .EmploymentStatus
                                            .EMPLOYED
                                    )
                                    .incomeCountry("income_country")
                                    .incomeSource(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .IncomeSource
                                            .FAMILY_SUPPORT
                                    )
                                    .incomeState("income_state")
                                    .industry(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .Industry
                                            .ACCOUNTING
                                    )
                                    .liveMode(true)
                                    .object_("object")
                                    .occupation(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .Occupation
                                            .CONSULTING
                                    )
                                    .sourceOfFunds(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .SourceOfFunds
                                            .ALIMONY
                                    )
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .wealthSource(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .WealthSource
                                            .BUSINESS_SALE
                                    )
                                    .build()
                            )
                            .website("website")
                            .build()
                    )
                    .childLegalEntityId("child_legal_entity_id")
                    .ownershipPercentage(0L)
                    .title("title")
                    .build()
            )
            .legalStructure(LegalEntityCreateParams.LegalStructure.CORPORATION)
            .metadata(
                LegalEntityCreateParams.Metadata.builder()
                    .putAdditionalProperty("key", JsonValue.from("value"))
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                    .build()
            )
            .middleName("middle_name")
            .addOperatingJurisdiction("string")
            .addPhoneNumber(
                LegalEntityCreateParams.PhoneNumber.builder().phoneNumber("phone_number").build()
            )
            .politicallyExposedPerson(true)
            .preferredName("preferred_name")
            .prefix("prefix")
            .addPrimarySocialMediaSite("string")
            .riskRating(LegalEntityCreateParams.RiskRating.LOW)
            .suffix("suffix")
            .wealthAndEmploymentDetails(
                LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .annualIncome(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .employerCountry("employer_country")
                    .employerName("employer_name")
                    .employerState("employer_state")
                    .employmentStatus(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.EmploymentStatus
                            .EMPLOYED
                    )
                    .incomeCountry("income_country")
                    .incomeSource(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.IncomeSource
                            .FAMILY_SUPPORT
                    )
                    .incomeState("income_state")
                    .industry(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.Industry
                            .ACCOUNTING
                    )
                    .liveMode(true)
                    .object_("object")
                    .occupation(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.Occupation
                            .CONSULTING
                    )
                    .sourceOfFunds(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.SourceOfFunds
                            .ALIMONY
                    )
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .wealthSource(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.WealthSource
                            .BUSINESS_SALE
                    )
                    .build()
            )
            .website("website")
            .build()
    }

    @Test
    fun body() {
        val params =
            LegalEntityCreateParams.builder()
                .legalEntityType(LegalEntityCreateParams.LegalEntityType.BUSINESS)
                .addAddress(
                    LegalEntityAddressCreateRequest.builder()
                        .country("country")
                        .line1("line1")
                        .locality("locality")
                        .postalCode("postal_code")
                        .region("region")
                        .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                        .line2("line2")
                        .build()
                )
                .bankSettings(
                    LegalEntityCreateParams.LegalEntityBankSetting.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .backupWithholdingPercentage(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .enableBackupWithholding(true)
                        .liveMode(true)
                        .object_("object")
                        .privacyOptOut(true)
                        .regulationO(true)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .businessDescription("business_description")
                .businessName("business_name")
                .citizenshipCountry("citizenship_country")
                .complianceDetails(
                    LegalEntityComplianceDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issuer("issuer")
                        .liveMode(true)
                        .object_("object")
                        .tokenExpiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .tokenUrl("token_url")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .entityValidated(true)
                        .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .countryOfIncorporation("country_of_incorporation")
                .dateFormed(LocalDate.parse("2019-12-27"))
                .dateOfBirth(LocalDate.parse("2019-12-27"))
                .addDoingBusinessAsName("string")
                .email("email")
                .expectedActivityVolume(0L)
                .firstName("first_name")
                .addIdentification(
                    IdentificationCreateRequest.builder()
                        .idNumber("id_number")
                        .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                        .expirationDate(LocalDate.parse("2019-12-27"))
                        .issuingCountry("issuing_country")
                        .issuingRegion("issuing_region")
                        .build()
                )
                .addIndustryClassification(
                    LegalEntityIndustryClassification.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .addClassificationCode("string")
                        .classificationType(
                            LegalEntityIndustryClassification.ClassificationType.ANZSIC
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .liveMode(true)
                        .object_("object")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .intendedUse("intended_use")
                .lastName("last_name")
                .addLegalEntityAssociation(
                    LegalEntityAssociationInlineCreate.builder()
                        .addRelationshipType(
                            LegalEntityAssociationInlineCreate.RelationshipType.AUTHORIZED_SIGNER
                        )
                        .childLegalEntity(
                            ChildLegalEntityCreate.builder()
                                .addAddress(
                                    LegalEntityAddressCreateRequest.builder()
                                        .country("country")
                                        .line1("line1")
                                        .locality("locality")
                                        .postalCode("postal_code")
                                        .region("region")
                                        .addAddressType(
                                            LegalEntityAddressCreateRequest.AddressType.BUSINESS
                                        )
                                        .line2("line2")
                                        .build()
                                )
                                .bankSettings(
                                    ChildLegalEntityCreate.LegalEntityBankSetting.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .backupWithholdingPercentage(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .enableBackupWithholding(true)
                                        .liveMode(true)
                                        .object_("object")
                                        .privacyOptOut(true)
                                        .regulationO(true)
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .businessDescription("business_description")
                                .businessName("business_name")
                                .citizenshipCountry("citizenship_country")
                                .complianceDetails(
                                    LegalEntityComplianceDetail.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .issuer("issuer")
                                        .liveMode(true)
                                        .object_("object")
                                        .tokenExpiresAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .tokenIssuedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .tokenUrl("token_url")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .entityValidated(true)
                                        .validatedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .build()
                                )
                                .countryOfIncorporation("country_of_incorporation")
                                .dateFormed(LocalDate.parse("2019-12-27"))
                                .dateOfBirth(LocalDate.parse("2019-12-27"))
                                .addDoingBusinessAsName("string")
                                .email("email")
                                .expectedActivityVolume(0L)
                                .firstName("first_name")
                                .addIdentification(
                                    IdentificationCreateRequest.builder()
                                        .idNumber("id_number")
                                        .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                                        .expirationDate(LocalDate.parse("2019-12-27"))
                                        .issuingCountry("issuing_country")
                                        .issuingRegion("issuing_region")
                                        .build()
                                )
                                .addIndustryClassification(
                                    LegalEntityIndustryClassification.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .addClassificationCode("string")
                                        .classificationType(
                                            LegalEntityIndustryClassification.ClassificationType
                                                .ANZSIC
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .intendedUse("intended_use")
                                .lastName("last_name")
                                .legalEntityAssociations(listOf())
                                .legalEntityType(ChildLegalEntityCreate.LegalEntityType.BUSINESS)
                                .legalStructure(ChildLegalEntityCreate.LegalStructure.CORPORATION)
                                .metadata(
                                    ChildLegalEntityCreate.Metadata.builder()
                                        .putAdditionalProperty("key", JsonValue.from("value"))
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                        .build()
                                )
                                .middleName("middle_name")
                                .addOperatingJurisdiction("string")
                                .addPhoneNumber(
                                    ChildLegalEntityCreate.PhoneNumber.builder()
                                        .phoneNumber("phone_number")
                                        .build()
                                )
                                .politicallyExposedPerson(true)
                                .preferredName("preferred_name")
                                .prefix("prefix")
                                .addPrimarySocialMediaSite("string")
                                .riskRating(ChildLegalEntityCreate.RiskRating.LOW)
                                .suffix("suffix")
                                .wealthAndEmploymentDetails(
                                    ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                        .builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .annualIncome(0L)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .discardedAt(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .employerCountry("employer_country")
                                        .employerName("employer_name")
                                        .employerState("employer_state")
                                        .employmentStatus(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .EmploymentStatus
                                                .EMPLOYED
                                        )
                                        .incomeCountry("income_country")
                                        .incomeSource(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .IncomeSource
                                                .FAMILY_SUPPORT
                                        )
                                        .incomeState("income_state")
                                        .industry(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .Industry
                                                .ACCOUNTING
                                        )
                                        .liveMode(true)
                                        .object_("object")
                                        .occupation(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .Occupation
                                                .CONSULTING
                                        )
                                        .sourceOfFunds(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .SourceOfFunds
                                                .ALIMONY
                                        )
                                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .wealthSource(
                                            ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                                .WealthSource
                                                .BUSINESS_SALE
                                        )
                                        .build()
                                )
                                .website("website")
                                .build()
                        )
                        .childLegalEntityId("child_legal_entity_id")
                        .ownershipPercentage(0L)
                        .title("title")
                        .build()
                )
                .legalStructure(LegalEntityCreateParams.LegalStructure.CORPORATION)
                .metadata(
                    LegalEntityCreateParams.Metadata.builder()
                        .putAdditionalProperty("key", JsonValue.from("value"))
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .putAdditionalProperty("modern", JsonValue.from("treasury"))
                        .build()
                )
                .middleName("middle_name")
                .addOperatingJurisdiction("string")
                .addPhoneNumber(
                    LegalEntityCreateParams.PhoneNumber.builder()
                        .phoneNumber("phone_number")
                        .build()
                )
                .politicallyExposedPerson(true)
                .preferredName("preferred_name")
                .prefix("prefix")
                .addPrimarySocialMediaSite("string")
                .riskRating(LegalEntityCreateParams.RiskRating.LOW)
                .suffix("suffix")
                .wealthAndEmploymentDetails(
                    LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .annualIncome(0L)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .employerCountry("employer_country")
                        .employerName("employer_name")
                        .employerState("employer_state")
                        .employmentStatus(
                            LegalEntityCreateParams.LegalEntityWealthEmploymentDetail
                                .EmploymentStatus
                                .EMPLOYED
                        )
                        .incomeCountry("income_country")
                        .incomeSource(
                            LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.IncomeSource
                                .FAMILY_SUPPORT
                        )
                        .incomeState("income_state")
                        .industry(
                            LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.Industry
                                .ACCOUNTING
                        )
                        .liveMode(true)
                        .object_("object")
                        .occupation(
                            LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.Occupation
                                .CONSULTING
                        )
                        .sourceOfFunds(
                            LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.SourceOfFunds
                                .ALIMONY
                        )
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .wealthSource(
                            LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.WealthSource
                                .BUSINESS_SALE
                        )
                        .build()
                )
                .website("website")
                .build()

        val body = params._body()

        assertThat(body.legalEntityType())
            .isEqualTo(LegalEntityCreateParams.LegalEntityType.BUSINESS)
        assertThat(body.addresses().getOrNull())
            .containsExactly(
                LegalEntityAddressCreateRequest.builder()
                    .country("country")
                    .line1("line1")
                    .locality("locality")
                    .postalCode("postal_code")
                    .region("region")
                    .addAddressType(LegalEntityAddressCreateRequest.AddressType.BUSINESS)
                    .line2("line2")
                    .build()
            )
        assertThat(body.bankSettings())
            .contains(
                LegalEntityCreateParams.LegalEntityBankSetting.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .backupWithholdingPercentage(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .enableBackupWithholding(true)
                    .liveMode(true)
                    .object_("object")
                    .privacyOptOut(true)
                    .regulationO(true)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(body.businessDescription()).contains("business_description")
        assertThat(body.businessName()).contains("business_name")
        assertThat(body.citizenshipCountry()).contains("citizenship_country")
        assertThat(body.complianceDetails())
            .contains(
                LegalEntityComplianceDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .issuer("issuer")
                    .liveMode(true)
                    .object_("object")
                    .tokenExpiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .tokenUrl("token_url")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .entityValidated(true)
                    .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(body.countryOfIncorporation()).contains("country_of_incorporation")
        assertThat(body.dateFormed()).contains(LocalDate.parse("2019-12-27"))
        assertThat(body.dateOfBirth()).contains(LocalDate.parse("2019-12-27"))
        assertThat(body.doingBusinessAsNames().getOrNull()).containsExactly("string")
        assertThat(body.email()).contains("email")
        assertThat(body.expectedActivityVolume()).contains(0L)
        assertThat(body.firstName()).contains("first_name")
        assertThat(body.identifications().getOrNull())
            .containsExactly(
                IdentificationCreateRequest.builder()
                    .idNumber("id_number")
                    .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                    .expirationDate(LocalDate.parse("2019-12-27"))
                    .issuingCountry("issuing_country")
                    .issuingRegion("issuing_region")
                    .build()
            )
        assertThat(body.industryClassifications().getOrNull())
            .containsExactly(
                LegalEntityIndustryClassification.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .addClassificationCode("string")
                    .classificationType(LegalEntityIndustryClassification.ClassificationType.ANZSIC)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .liveMode(true)
                    .object_("object")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(body.intendedUse()).contains("intended_use")
        assertThat(body.lastName()).contains("last_name")
        assertThat(body.legalEntityAssociations().getOrNull())
            .containsExactly(
                LegalEntityAssociationInlineCreate.builder()
                    .addRelationshipType(
                        LegalEntityAssociationInlineCreate.RelationshipType.AUTHORIZED_SIGNER
                    )
                    .childLegalEntity(
                        ChildLegalEntityCreate.builder()
                            .addAddress(
                                LegalEntityAddressCreateRequest.builder()
                                    .country("country")
                                    .line1("line1")
                                    .locality("locality")
                                    .postalCode("postal_code")
                                    .region("region")
                                    .addAddressType(
                                        LegalEntityAddressCreateRequest.AddressType.BUSINESS
                                    )
                                    .line2("line2")
                                    .build()
                            )
                            .bankSettings(
                                ChildLegalEntityCreate.LegalEntityBankSetting.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .backupWithholdingPercentage(0L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .enableBackupWithholding(true)
                                    .liveMode(true)
                                    .object_("object")
                                    .privacyOptOut(true)
                                    .regulationO(true)
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .businessDescription("business_description")
                            .businessName("business_name")
                            .citizenshipCountry("citizenship_country")
                            .complianceDetails(
                                LegalEntityComplianceDetail.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .issuer("issuer")
                                    .liveMode(true)
                                    .object_("object")
                                    .tokenExpiresAt(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .tokenIssuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .tokenUrl("token_url")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .entityValidated(true)
                                    .validatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .countryOfIncorporation("country_of_incorporation")
                            .dateFormed(LocalDate.parse("2019-12-27"))
                            .dateOfBirth(LocalDate.parse("2019-12-27"))
                            .addDoingBusinessAsName("string")
                            .email("email")
                            .expectedActivityVolume(0L)
                            .firstName("first_name")
                            .addIdentification(
                                IdentificationCreateRequest.builder()
                                    .idNumber("id_number")
                                    .idType(IdentificationCreateRequest.IdType.AR_CUIL)
                                    .expirationDate(LocalDate.parse("2019-12-27"))
                                    .issuingCountry("issuing_country")
                                    .issuingRegion("issuing_region")
                                    .build()
                            )
                            .addIndustryClassification(
                                LegalEntityIndustryClassification.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .addClassificationCode("string")
                                    .classificationType(
                                        LegalEntityIndustryClassification.ClassificationType.ANZSIC
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .liveMode(true)
                                    .object_("object")
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .intendedUse("intended_use")
                            .lastName("last_name")
                            .legalEntityAssociations(listOf())
                            .legalEntityType(ChildLegalEntityCreate.LegalEntityType.BUSINESS)
                            .legalStructure(ChildLegalEntityCreate.LegalStructure.CORPORATION)
                            .metadata(
                                ChildLegalEntityCreate.Metadata.builder()
                                    .putAdditionalProperty("key", JsonValue.from("value"))
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                                    .build()
                            )
                            .middleName("middle_name")
                            .addOperatingJurisdiction("string")
                            .addPhoneNumber(
                                ChildLegalEntityCreate.PhoneNumber.builder()
                                    .phoneNumber("phone_number")
                                    .build()
                            )
                            .politicallyExposedPerson(true)
                            .preferredName("preferred_name")
                            .prefix("prefix")
                            .addPrimarySocialMediaSite("string")
                            .riskRating(ChildLegalEntityCreate.RiskRating.LOW)
                            .suffix("suffix")
                            .wealthAndEmploymentDetails(
                                ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .annualIncome(0L)
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .employerCountry("employer_country")
                                    .employerName("employer_name")
                                    .employerState("employer_state")
                                    .employmentStatus(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .EmploymentStatus
                                            .EMPLOYED
                                    )
                                    .incomeCountry("income_country")
                                    .incomeSource(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .IncomeSource
                                            .FAMILY_SUPPORT
                                    )
                                    .incomeState("income_state")
                                    .industry(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .Industry
                                            .ACCOUNTING
                                    )
                                    .liveMode(true)
                                    .object_("object")
                                    .occupation(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .Occupation
                                            .CONSULTING
                                    )
                                    .sourceOfFunds(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .SourceOfFunds
                                            .ALIMONY
                                    )
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .wealthSource(
                                        ChildLegalEntityCreate.LegalEntityWealthEmploymentDetail
                                            .WealthSource
                                            .BUSINESS_SALE
                                    )
                                    .build()
                            )
                            .website("website")
                            .build()
                    )
                    .childLegalEntityId("child_legal_entity_id")
                    .ownershipPercentage(0L)
                    .title("title")
                    .build()
            )
        assertThat(body.legalStructure())
            .contains(LegalEntityCreateParams.LegalStructure.CORPORATION)
        assertThat(body.metadata())
            .contains(
                LegalEntityCreateParams.Metadata.builder()
                    .putAdditionalProperty("key", JsonValue.from("value"))
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .putAdditionalProperty("modern", JsonValue.from("treasury"))
                    .build()
            )
        assertThat(body.middleName()).contains("middle_name")
        assertThat(body.operatingJurisdictions().getOrNull()).containsExactly("string")
        assertThat(body.phoneNumbers().getOrNull())
            .containsExactly(
                LegalEntityCreateParams.PhoneNumber.builder().phoneNumber("phone_number").build()
            )
        assertThat(body.politicallyExposedPerson()).contains(true)
        assertThat(body.preferredName()).contains("preferred_name")
        assertThat(body.prefix()).contains("prefix")
        assertThat(body.primarySocialMediaSites().getOrNull()).containsExactly("string")
        assertThat(body.riskRating()).contains(LegalEntityCreateParams.RiskRating.LOW)
        assertThat(body.suffix()).contains("suffix")
        assertThat(body.wealthAndEmploymentDetails())
            .contains(
                LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .annualIncome(0L)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .discardedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .employerCountry("employer_country")
                    .employerName("employer_name")
                    .employerState("employer_state")
                    .employmentStatus(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.EmploymentStatus
                            .EMPLOYED
                    )
                    .incomeCountry("income_country")
                    .incomeSource(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.IncomeSource
                            .FAMILY_SUPPORT
                    )
                    .incomeState("income_state")
                    .industry(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.Industry
                            .ACCOUNTING
                    )
                    .liveMode(true)
                    .object_("object")
                    .occupation(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.Occupation
                            .CONSULTING
                    )
                    .sourceOfFunds(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.SourceOfFunds
                            .ALIMONY
                    )
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .wealthSource(
                        LegalEntityCreateParams.LegalEntityWealthEmploymentDetail.WealthSource
                            .BUSINESS_SALE
                    )
                    .build()
            )
        assertThat(body.website()).contains("website")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            LegalEntityCreateParams.builder()
                .legalEntityType(LegalEntityCreateParams.LegalEntityType.BUSINESS)
                .build()

        val body = params._body()

        assertThat(body.legalEntityType())
            .isEqualTo(LegalEntityCreateParams.LegalEntityType.BUSINESS)
    }
}
